import numpy as np

SEED = 1234
RNG = np.random.default_rng(SEED)

KILOMETER = 1_000.0
MINUTE = 60.0
HOUR = 60 * MINUTE
DAY = 24 * HOUR

R_EARTH = 6_371 * KILOMETER
MIN_R_MAG = R_EARTH
MAX_R_MAG = R_EARTH + 69_000 * KILOMETER
MIN_V_MAG = 0.0
MAX_V_MAG = 12 * KILOMETER

MIN_THRUST = 0.0
MAX_THRUST = KILOMETER

MIN_TIME_STEP_SEC = MINUTE
MAX_TIME_STEP_SEC = HOUR
